---
title: "Gov 50 Final Project"
author: "Julia English"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to rural education access data possibly through the Urban institute data. Or I was thinking about district spending data though Georgetown's National Education Resource Database on Schools. My next step would be to look through these data sets and see if there are any interesting facets. 


## Proposal

What affects teacher retention? For this data analysis, I'm interested in working with the Massachusetts Department of Education Schools and Districts data set. Right now there is a teacher shortage. However, because of contracted pay schedules and teacher pay being the greatest expenditure schools are searching for non-monetary ways to increase teacher retention. My theory is that quality of life aspects, not just pay would also influence retention. I'm hoping to look at incidence of in-school or out of school suspension, average class size, and number of class preps. My outcome variable would be teacher retention rate on the school level, measured in percent. My predictor variable would be average class size measured in number of students, in-school and out of school suspensions measured in percents and average class preps measured in number of classes. I want to run a multiple regression as variables in education are usually intertwined. For example a higher class size might have a higher rate of behavioral referrals. Holding these covariants constant and still seeing a statistically significant association would be convincing evidence.  
